import type { Project, DashboardLead } from "../types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    code: "AC-8821",
    name: "锦绣华城 - 3期 A栋",
    location: "静安区",
    specs: "128㎡ · 3室2厅",
    stats: {
      viewTotal: 142,
      viewTrend: { current: 12, last: 8, isUp: true },
      offerCount: 5,
      maxOffer: 820,
      lastOffer: 815,
    },
    market: {
      onSale: 12,
      avgPrice: "6.8万/㎡",
      volume30d: 4,
      priceTrend30d: "-1.2% ↓",
      isPriceUp: false,
    },
  },
  {
    id: "2",
    code: "AC-9012",
    name: "东方曼哈顿 - 2单元",
    location: "徐汇区",
    specs: "156㎡ · 4室2厅",
    stats: {
      viewTotal: 205,
      viewTrend: { current: 24, last: 15, isUp: true },
      offerCount: 8,
      maxOffer: 1250,
      lastOffer: 1240,
    },
    market: {
      onSale: 5,
      avgPrice: "8.2万/㎡",
      volume30d: 2,
      priceTrend30d: "+0.5% ↑",
      isPriceUp: true,
    },
  },
  {
    id: "3",
    code: "AC-4432",
    name: "仁恒河滨城",
    location: "浦东新区",
    specs: "89㎡ · 2室2厅",
    stats: {
      viewTotal: 56,
      viewTrend: { current: 2, last: 5, isUp: false },
      offerCount: 1,
      maxOffer: 580,
      lastOffer: 580,
    },
    market: {
      onSale: 18,
      avgPrice: "6.4万/㎡",
      volume30d: 1,
      priceTrend30d: "持平",
      isPriceUp: null,
    },
  },
];

export const MOCK_LEADS: DashboardLead[] = [
  {
    id: "l1",
    community: "锦绣华城 - 3期 A栋",
    unitType: "3室2厅",
    area: "128㎡",
    floor: "12/28",
    totalPrice: "820万",
    unitPrice: "6.4万/㎡",
    status: "带看中",
    region: "静安区",
    creator: "李晓梅",
    updatedTime: "2小时前",
  },
  {
    id: "l2",
    community: "东方曼哈顿 - 2单元",
    unitType: "4室2厅",
    area: "156㎡",
    floor: "6/12",
    totalPrice: "1250万",
    unitPrice: "8.0万/㎡",
    status: "已出价",
    region: "徐汇区",
    creator: "陈大卫",
    updatedTime: "5小时前",
  },
  {
    id: "l3",
    community: "仁恒河滨城",
    unitType: "2室2厅",
    area: "89㎡",
    floor: "18/32",
    totalPrice: "580万",
    unitPrice: "6.5万/㎡",
    status: "初步评估",
    region: "浦东新区",
    creator: "王五",
    updatedTime: "昨天 16:30",
  },
];
