"""系统预置科目种子数据.

存放 finance_subjects 表的 37 条系统预置科目（S01-S37），由 create_finance_subjects_table
幂等插入（按 name 去重）。本模块仅包含纯 Python 数据，无副作用，无外部依赖。

数据来源：docs/designs/profocw-record-demo/三模块.html 的 INITIAL_SUBJECTS 常量。
字段：id/name/level/pnl/modes/stage/note。
"""

# 系统预置科目种子数据（37 条 S01-S37）。
# 数据来源：docs/designs/profocw-record-demo/三模块.html 的 INITIAL_SUBJECTS 常量。
# 字段：id/name/level/pnl/modes/stage/note；由 create_finance_subjects_table 幂等插入（按 name 去重）。
_INITIAL_SUBJECTS: list[dict] = [
    # ①取得成本（仅收购）
    {
        "id": "S01",
        "name": "购房定金",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购专有 · 计入售房差额",
    },
    {
        "id": "S02",
        "name": "购房首付",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购专有 · 计入售房差额",
    },
    {
        "id": "S03",
        "name": "购房尾款",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购专有 · 计入售房差额",
    },
    {
        "id": "S04",
        "name": "购房贷款差额",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购专有 · 贷款不足补差额",
    },
    {
        "id": "S05",
        "name": "交易税费(买入)",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购专有 · 过户买方税费",
    },
    {
        "id": "S06",
        "name": "购房名额使用费",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购专有 · 代持人名额费",
    },
    {
        "id": "S07",
        "name": "月供利息",
        "level": "1",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "holding",
        "note": "已含于售房差额 · 月供拆分",
    },
    # ②直接改造成本
    {
        "id": "S08",
        "name": "设计费",
        "level": "2",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "renovation",
        "note": "扣减毛利",
    },
    {
        "id": "S09",
        "name": "装修款",
        "level": "2",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "renovation",
        "note": "扣减毛利",
    },
    {
        "id": "S10",
        "name": "软装采购",
        "level": "2",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "renovation",
        "note": "可选 · 按实际",
    },
    # ③交易费用
    {
        "id": "S11",
        "name": "收房佣金",
        "level": "3",
        "pnl": True,
        "modes": ["agent"],
        "stage": "signing",
        "note": "代理 · 毛利层扣减",
    },
    {
        "id": "S12",
        "name": "购房佣金",
        "level": "3",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "收购 · 毛利层扣减",
    },
    {
        "id": "S13",
        "name": "售房佣金",
        "level": "3",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "收购 · 毛利层扣减",
    },
    {
        "id": "S14",
        "name": "营销推广费",
        "level": "3",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "listing",
        "note": "代理=卖出价×0.5% · 含推广支出",
    },
    {
        "id": "S15",
        "name": "销售额外激励",
        "level": "3",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "listing",
        "note": "如iPhone奖励 · 独立于营销推广费",
    },
    {
        "id": "S16",
        "name": "营销支出其他",
        "level": "3",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "listing",
        "note": "如纱窗/除甲醛 · 独立于营销推广费",
    },
    {
        "id": "S17",
        "name": "运营服务费",
        "level": "3",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "sold",
        "note": "代理=卖出价×1%",
    },
    {
        "id": "S18",
        "name": "卖房佣金差额",
        "level": "3",
        "pnl": True,
        "modes": ["agent"],
        "stage": "sold",
        "note": "仅代理 · 差价×1% · 佣金差额(非税费)",
    },
    {
        "id": "S19",
        "name": "差额税费",
        "level": "3",
        "pnl": True,
        "modes": ["agent"],
        "stage": "sold",
        "note": "仅代理 · 差价×1%+个税",
    },
    {
        "id": "S20",
        "name": "交易税费(卖出)",
        "level": "3",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "仅收购 · 卖方全额税费",
    },
    # ④资金成本
    {
        "id": "S21",
        "name": "项目分润",
        "level": "4",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "sold",
        "note": "付融资方利润 · 扣减净利润",
    },
    # ⑤现金流专属
    {
        "id": "S22",
        "name": "月供本金",
        "level": "5",
        "pnl": False,
        "modes": ["acquire"],
        "stage": "holding",
        "note": "资产负债项 · 不进损益 · 月供拆分",
    },
    {
        "id": "S23",
        "name": "贷款发放",
        "level": "5",
        "pnl": False,
        "modes": ["acquire"],
        "stage": "signing",
        "note": "银行放款 · 资产负债项 · 流入",
    },
    {
        "id": "S24",
        "name": "卖房还贷",
        "level": "5",
        "pnl": False,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "仅情况二 · 投资款垫付 · 不进损益",
    },
    {
        "id": "S25",
        "name": "投资款收入",
        "level": "5",
        "pnl": False,
        "modes": ["agent", "acquire"],
        "stage": "signing",
        "note": "股东本金往来 · 不进损益",
    },
    {
        "id": "S26",
        "name": "投资款还本",
        "level": "5",
        "pnl": False,
        "modes": ["agent", "acquire"],
        "stage": "sold",
        "note": "归还股东本金 · 不进损益",
    },
    # ⑥收入项
    {
        "id": "S27",
        "name": "增值服务费",
        "level": "6",
        "pnl": True,
        "modes": ["agent"],
        "stage": "sold",
        "note": "代理核心收入 = 卖出价−业主底价",
    },
    {
        "id": "S28",
        "name": "售房差额",
        "level": "6",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "收购核心收入 = 卖出价−(取得成本+月供利息)",
    },
    {
        "id": "S29",
        "name": "收卖房定金",
        "level": "6",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "三项合计=卖出价",
    },
    {
        "id": "S30",
        "name": "收卖房首付",
        "level": "6",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "三项合计=卖出价",
    },
    {
        "id": "S31",
        "name": "收卖房尾款",
        "level": "6",
        "pnl": True,
        "modes": ["acquire"],
        "stage": "sold",
        "note": "三项合计=卖出价",
    },
    {
        "id": "S32",
        "name": "他项收入",
        "level": "6",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "sold",
        "note": "非主业收入",
    },
    {
        "id": "S33",
        "name": "结算差额",
        "level": "6",
        "pnl": True,
        "modes": ["agent", "acquire"],
        "stage": "sold",
        "note": "兜底平账",
    },
    # ⑦配对项
    {
        "id": "S34",
        "name": "履约保证金",
        "level": "7",
        "pnl": False,
        "modes": ["agent"],
        "stage": "signing",
        "note": '配对"业主保证金回退" · 净额归零',
    },
    {
        "id": "S35",
        "name": "业主保证金回退",
        "level": "7",
        "pnl": False,
        "modes": ["agent"],
        "stage": "sold",
        "note": '配对"履约保证金" · 净额归零',
    },
    {
        "id": "S36",
        "name": "暂支款(垫付)",
        "level": "7",
        "pnl": False,
        "modes": ["agent", "acquire"],
        "stage": "renovation",
        "note": '配对"暂支款核销" · 净额归零',
    },
    {
        "id": "S37",
        "name": "暂支款核销",
        "level": "7",
        "pnl": False,
        "modes": ["agent", "acquire"],
        "stage": "listing",
        "note": '配对"暂支款(垫付)" · 净额归零',
    },
]
